# F3V3R DR34M - G1THU8 D3PL0YM3NT H4X

name: Deploy to GitHub Pages
# TR1GG3R 0N M41N BR4NCH PU5H
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# S3T UP D3PL0YM3NT P3RM1SS10N5
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # ULT1M4T3 D3PL0YM3NT J08
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # CH3CK0UT C0D3 R3P0
      - name: Checkout
        uses: actions/checkout@v4

      # S3TUP N0D3.JS 3NV
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 1N5T4LL D3P3ND3NC13Z
      - name: Install dependencies
        run: npm ci

      # 8U1LD PR0J3CT (1F N33D3D)
      - name: Build Project
        run: npm run build || echo "No build script found"

      # S3TUP G1THUB P4G3Z
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # UPL04D 4RT1F4CTZ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # D3PL0Y 3NT1R3 R3P0

      # D3PL0Y T0 G1THUB P4G3Z
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
